services:
  web:
    image: flaviofrancisco/vagasprajr-web
    container_name: vagasprajr-ui
    hostname: ui
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_HOST=http://api:3001
    networks:
      vagasprajr_network:
        ipv4_address: 172.16.238.8            

  api:
    image: flaviofrancisco/vagasprajr-api
    container_name: vagasprajr-api
    hostname: api
    dns_search: ''
    env_file:
      - .env         
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/uploads:rw
      - ./.env:/app/.env:ro
      - ./api/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - DEBUG_MODE=true
      - MONGO_URI=mongodb://admin:Your_Super_Secret_Password_For_MongoDB_Root_User_Account_123_456_789@db:27017/vagasprajrdb?authSource=admin
      - JWT_SECRET=Your_Super_Secret_JWT_Secret_123_456_789      
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=false   
      - MONGODB_DATABASE=vagasprajrdb
      - BASE_UI_HOST=http://ui:3000
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      vagasprajr_network:
        ipv4_address: 172.16.238.9      

  db:
    image: flaviofrancisco/vagasprajr-db
    container_name: vagasprajr-db
    hostname: db
    volumes:
      - ./db:/data/db # Replace with your volume mapping if needed
      - ./backup:/backup # Replace with your volume mapping if needed
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Your_Super_Secret_Password_For_MongoDB_Root_User_Account_123_456_789      
    ports:
      - "27017:27017"
    networks:
      vagasprajr_network:
        ipv4_address: 172.16.238.10  

  redis:
    image: redis:alpine
    container_name: vagasprajr-redis
    hostname: redis
    env_file:
      - .env       
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # Specify the redis.conf file to use and add a password.
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}      
    ports:
      - "6379:6379"
    networks:
      vagasprajr_network:
        ipv4_address: 172.16.238.11              

networks:
  vagasprajr_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24    

volumes:
  uploads:       
          
